"""Flavor-owned relative paths for cross-platform host fixtures."""

from __future__ import annotations

from pathlib import PurePosixPath, PureWindowsPath


PureHostPath = PurePosixPath | PureWindowsPath


def relative_host_path(target: PureHostPath, base: PureHostPath) -> PureHostPath:
    """Return ``target`` relative to ``base`` without host-OS guessing.

    Both inputs must already use the same explicit ``pathlib`` flavor and the
    same absolute namespace. POSIX components compare case-sensitively;
    Windows drive and UNC components compare case-insensitively. Parent
    segments are generated by this trusted boundary rather than accepted from
    caller text.
    """

    target_is_windows = isinstance(target, PureWindowsPath)
    base_is_windows = isinstance(base, PureWindowsPath)
    if target_is_windows != base_is_windows:
        raise ValueError("target and base must use the same host-path flavor")
    if not target.is_absolute() or not base.is_absolute():
        raise ValueError("target and base must be absolute host paths")

    compare = str.casefold if target_is_windows else _identity
    if compare(target.anchor) != compare(base.anchor):
        raise ValueError("target and base must share one drive or UNC namespace")

    target_parts = target.parts[1:]
    base_parts = base.parts[1:]
    shared_count = 0
    for target_part, base_part in zip(target_parts, base_parts, strict=False):
        if compare(target_part) != compare(base_part):
            break
        shared_count += 1

    relative_parts = (
        *(".." for _ in base_parts[shared_count:]),
        *target_parts[shared_count:],
    )
    path_type = PureWindowsPath if target_is_windows else PurePosixPath
    return path_type(*relative_parts) if relative_parts else path_type(".")


def _identity(value: str) -> str:
    return value


__all__ = ["PureHostPath", "relative_host_path"]
