"""Structured semantic intent and plan contracts for WAAPI planning.

This module is intentionally schema-only: it validates typed intent envelopes and
serializes closed plan records, but it does not parse prose, call builders, or
dispatch WAAPI requests.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Sequence, cast

from wwise_waapi.builders.common import SemanticErrorCode, SemanticValidationError


SEMANTIC_CONFIRMATION_STATES = ("unknown", "preview", "confirmed", "rejected")
SUPPORTED_SEMANTIC_FAMILIES = (
    "intent_navigation",
    "crud_authoring",
    "system_design_preview",
    "asset_import_workflow",
    "soundbank_workflow",
    "switch_assignment_workflow",
    "bounded_profiler_guidance",
    "unsupported_runtime_boundary",
)
SEMANTIC_FAMILY_BUILDER_REFS: Mapping[str, tuple[str, ...]] = {
    "intent_navigation": ("wwise_waapi.builders.query",),
    "crud_authoring": ("wwise_waapi.builders.object_mutation", "wwise_waapi.builders.properties"),
    "system_design_preview": (
        "wwise_waapi.builders.query",
        "wwise_waapi.builders.object_mutation",
        "wwise_waapi.builders.properties",
        "wwise_waapi.builders.imports",
    ),
    "asset_import_workflow": ("wwise_waapi.builders.imports",),
    "soundbank_workflow": ("wwise_waapi.builders.soundbank",),
    "switch_assignment_workflow": ("wwise_waapi.builders.switchcontainer",),
    "bounded_profiler_guidance": ("wwise_waapi.builders.profiler",),
    "unsupported_runtime_boundary": (),
}


class SemanticPlanStatus(str, Enum):
    """Closed status values for schema-only semantic plans."""

    READY = "ready"
    BLOCKED = "blocked"
    NEEDS_CLARIFICATION = "needs_clarification"
    UNSUPPORTED = "unsupported"


@dataclass(slots=True, frozen=True)
class SemanticIntentTarget:
    """One structured target supplied by the caller's semantic intent envelope."""

    kind: str
    identifier: str
    display_name: str = ""
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "identifier": self.identifier,
            "display_name": self.display_name,
            "metadata": _json_safe_mapping(self.metadata),
        }


@dataclass(slots=True, frozen=True)
class SemanticIntentConstraint:
    """One typed constraint supplied by a caller before planning."""

    field: str
    operator: str
    value: Any
    reason: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "field": self.field,
            "operator": self.operator,
            "value": _json_safe(self.value),
            "reason": self.reason,
        }


@dataclass(slots=True, frozen=True)
class SemanticIntent:
    """Structured planner input; arbitrary natural-language strings are not accepted."""

    family: str
    goal: str
    version: str
    targets: Sequence[SemanticIntentTarget | Mapping[str, Any]]
    constraints: Sequence[SemanticIntentConstraint | Mapping[str, Any]]
    requested_operations: Sequence[str]
    confirmation_state: str
    source_prompt_excerpt: str

    def __post_init__(self) -> None:
        _require_supported_family(self.family)
        if not self.goal:
            raise SemanticValidationError(
                SemanticErrorCode.SEMANTIC_SCHEMA_MISMATCH,
                "Semantic intent requires a non-empty goal.",
                details={"field": "goal"},
            )
        _require_confirmation_state(self.confirmation_state)
        object.__setattr__(self, "targets", tuple(_intent_target(target) for target in self.targets))
        object.__setattr__(self, "constraints", tuple(_intent_constraint(constraint) for constraint in self.constraints))
        object.__setattr__(self, "requested_operations", tuple(str(operation) for operation in self.requested_operations))

    def as_dict(self) -> dict[str, Any]:
        targets = cast(tuple[SemanticIntentTarget, ...], self.targets)
        constraints = cast(tuple[SemanticIntentConstraint, ...], self.constraints)
        return {
            "family": self.family,
            "goal": self.goal,
            "version": self.version,
            "targets": [target.as_dict() for target in targets],
            "constraints": [constraint.as_dict() for constraint in constraints],
            "requested_operations": list(self.requested_operations),
            "confirmation_state": self.confirmation_state,
            "source_prompt_excerpt": self.source_prompt_excerpt,
        }


@dataclass(slots=True, frozen=True)
class SemanticPlanPreview:
    """Serializable preview identity generated by a later builder-backed planner."""

    preview_id: str
    preview_hash: str
    summary: str = ""
    payload: Mapping[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "preview_id": self.preview_id,
            "preview_hash": self.preview_hash,
            "summary": self.summary,
            "payload": _json_safe_mapping(self.payload),
        }


@dataclass(slots=True, frozen=True)
class SemanticPlanVerification:
    """One deterministic verification step expected after preview or execution."""

    kind: str
    description: str
    preview_hash: str = ""
    readback_plan: Mapping[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "description": self.description,
            "preview_hash": self.preview_hash,
            "readback_plan": _json_safe_mapping(self.readback_plan),
        }


@dataclass(slots=True, frozen=True)
class SemanticPlanStep:
    """Closed schema for one future planner step; no dispatch behavior is attached."""

    step_id: str
    operation: str
    family: str
    preview: SemanticPlanPreview | Mapping[str, Any] | None = None
    inputs: Mapping[str, Any] = field(default_factory=dict)
    source_builder_ref: str = ""

    def __post_init__(self) -> None:
        _require_supported_family(self.family)
        if self.preview is not None and not isinstance(self.preview, SemanticPlanPreview):
            object.__setattr__(self, "preview", _plan_preview(self.preview))

    def as_dict(self) -> dict[str, Any]:
        preview = cast(SemanticPlanPreview | None, self.preview)
        return {
            "step_id": self.step_id,
            "operation": self.operation,
            "family": self.family,
            "preview": preview.as_dict() if preview is not None else None,
            "inputs": _json_safe_mapping(self.inputs),
            "source_builder_ref": self.source_builder_ref,
        }


@dataclass(slots=True, frozen=True)
class SemanticPlan:
    """Top-level semantic plan envelope returned by the schema-only planner."""

    status: SemanticPlanStatus | str
    family: str
    version: str
    steps: Sequence[SemanticPlanStep | Mapping[str, Any]]
    preview_id: str
    preview_hash: str
    risk_flags: Sequence[str]
    requires_confirmation: bool
    blocked_reason: str
    needs_clarification: bool
    unsupported_capability: bool
    verification_steps: Sequence[SemanticPlanVerification | Mapping[str, Any]]
    source_builder_refs: Sequence[str]

    def __post_init__(self) -> None:
        _require_supported_family(self.family)
        status = SemanticPlanStatus(self.status)
        object.__setattr__(self, "status", status)
        object.__setattr__(self, "steps", tuple(_plan_step(step) for step in self.steps))
        object.__setattr__(self, "risk_flags", tuple(str(flag) for flag in self.risk_flags))
        object.__setattr__(self, "verification_steps", tuple(_plan_verification(step) for step in self.verification_steps))
        object.__setattr__(self, "source_builder_refs", tuple(str(ref) for ref in self.source_builder_refs))

    def as_dict(self) -> dict[str, Any]:
        status = cast(SemanticPlanStatus, self.status)
        steps = cast(tuple[SemanticPlanStep, ...], self.steps)
        verification_steps = cast(tuple[SemanticPlanVerification, ...], self.verification_steps)
        return {
            "status": status.value,
            "family": self.family,
            "version": self.version,
            "steps": [step.as_dict() for step in steps],
            "preview_id": self.preview_id,
            "preview_hash": self.preview_hash,
            "risk_flags": list(self.risk_flags),
            "requires_confirmation": self.requires_confirmation,
            "blocked_reason": self.blocked_reason,
            "needs_clarification": self.needs_clarification,
            "unsupported_capability": self.unsupported_capability,
            "verification_steps": [step.as_dict() for step in verification_steps],
            "source_builder_refs": list(self.source_builder_refs),
        }


class SemanticPlanner:
    """Schema-only planner boundary that accepts typed intent envelopes only."""

    def plan(self, intent: SemanticIntent) -> SemanticPlan:
        if not isinstance(intent, SemanticIntent):
            raise SemanticValidationError(
                SemanticErrorCode.SEMANTIC_SCHEMA_MISMATCH,
                "Semantic planner input must be a structured SemanticIntent.",
                details={"expected": "SemanticIntent", "received": type(intent).__name__},
            )
        _require_supported_family(intent.family)

        if intent.family == "unsupported_runtime_boundary":
            return SemanticPlan(
                status=SemanticPlanStatus.UNSUPPORTED,
                family=intent.family,
                version=intent.version,
                steps=(),
                preview_id="",
                preview_hash="",
                risk_flags=(),
                requires_confirmation=False,
                blocked_reason="runtime orchestration capabilities are outside the WAAPI authoring planner boundary",
                needs_clarification=False,
                unsupported_capability=True,
                verification_steps=(),
                source_builder_refs=(),
            )

        return SemanticPlan(
            status=SemanticPlanStatus.BLOCKED,
            family=intent.family,
            version=intent.version,
            steps=(),
            preview_id="",
            preview_hash="",
            risk_flags=(),
            requires_confirmation=intent.confirmation_state != "confirmed",
            blocked_reason="semantic planner routing skeleton records allowed builders but does not execute builder previews",
            needs_clarification=False,
            unsupported_capability=False,
            verification_steps=(),
            source_builder_refs=SEMANTIC_FAMILY_BUILDER_REFS[intent.family],
        )


def _require_supported_family(family: str) -> None:
    if family not in SUPPORTED_SEMANTIC_FAMILIES:
        raise SemanticValidationError(
            SemanticErrorCode.UNSUPPORTED_BUILDER_FAMILY,
            f"Unsupported semantic intent family: {family!r}",
            details={"family": family, "supported": list(SUPPORTED_SEMANTIC_FAMILIES)},
        )


def _require_confirmation_state(confirmation_state: str) -> None:
    if confirmation_state not in SEMANTIC_CONFIRMATION_STATES:
        raise SemanticValidationError(
            SemanticErrorCode.SEMANTIC_SCHEMA_MISMATCH,
            f"Unsupported semantic confirmation state: {confirmation_state!r}",
            details={"confirmation_state": confirmation_state, "supported": list(SEMANTIC_CONFIRMATION_STATES)},
        )


def _intent_target(value: SemanticIntentTarget | Mapping[str, Any]) -> SemanticIntentTarget:
    if isinstance(value, SemanticIntentTarget):
        return value
    return SemanticIntentTarget(
        kind=str(value["kind"]),
        identifier=str(value["identifier"]),
        display_name=str(value.get("display_name", "")),
        metadata=_mapping_value(value.get("metadata", {})),
    )


def _intent_constraint(value: SemanticIntentConstraint | Mapping[str, Any]) -> SemanticIntentConstraint:
    if isinstance(value, SemanticIntentConstraint):
        return value
    return SemanticIntentConstraint(
        field=str(value["field"]),
        operator=str(value["operator"]),
        value=value["value"],
        reason=str(value.get("reason", "")),
    )


def _plan_preview(value: SemanticPlanPreview | Mapping[str, Any]) -> SemanticPlanPreview:
    if isinstance(value, SemanticPlanPreview):
        return value
    return SemanticPlanPreview(
        preview_id=str(value["preview_id"]),
        preview_hash=str(value["preview_hash"]),
        summary=str(value.get("summary", "")),
        payload=_mapping_value(value.get("payload", {})),
    )


def _plan_verification(value: SemanticPlanVerification | Mapping[str, Any]) -> SemanticPlanVerification:
    if isinstance(value, SemanticPlanVerification):
        return value
    return SemanticPlanVerification(
        kind=str(value["kind"]),
        description=str(value["description"]),
        preview_hash=str(value.get("preview_hash", "")),
        readback_plan=_mapping_value(value.get("readback_plan", {})),
    )


def _plan_step(value: SemanticPlanStep | Mapping[str, Any]) -> SemanticPlanStep:
    if isinstance(value, SemanticPlanStep):
        return value
    return SemanticPlanStep(
        step_id=str(value["step_id"]),
        operation=str(value["operation"]),
        family=str(value["family"]),
        preview=value.get("preview"),
        inputs=_mapping_value(value.get("inputs", {})),
        source_builder_ref=str(value.get("source_builder_ref", "")),
    )


def _mapping_value(value: Any) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise SemanticValidationError(
            SemanticErrorCode.SEMANTIC_SCHEMA_MISMATCH,
            "Semantic planner metadata fields must be mappings.",
            details={"received": type(value).__name__},
        )
    return value


def _json_safe_mapping(value: Mapping[str, Any]) -> dict[str, Any]:
    return {str(key): _json_safe(item) for key, item in value.items()}


def _json_safe(value: Any) -> Any:
    if hasattr(value, "as_dict"):
        return value.as_dict()
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Mapping):
        return _json_safe_mapping(value)
    if isinstance(value, (tuple, list)):
        return [_json_safe(item) for item in value]
    return value
